name: .NET

on:
  push:
    branches: [ dev*, main ]
  pull_request:
    branches: [ main ]
    paths:
      - src/*
      - .github/workflows/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build src/Chat.Api/Chat.Api.csproj --no-restore
    - name: Test
      run: dotnet test src/Chat.Domain.Tests/Chat.Domain.Tests.csproj --no-build --verbosity normal
